#!/bin/sh

# Note: currently only installs rcm

curl -LO https://thoughtbot.github.io/rcm/dist/rcm-1.3.0.tar.gz && \

sha=$(sha256 rcm-1.3.0.tar.gz | cut -f1 -d' ') && \
[ "$sha" = "502fd44e567ed0cfd00fb89ccc257dac8d6eb5d003f121299b5294c01665973f" ] && \

tar -xvf rcm-1.3.0.tar.gz && \
cd rcm-1.3.0 && \

./configure && \
make && \
sudo make install
